"""
TeX Lookup Python library.

Provides a means of converting a symbol index to it's corresponding TeX markup.
"""

#build array for enumeration
characterSet = {}
characterSet[0] = '0'
characterSet[1] = '1'
characterSet[2] = '2'
characterSet[3] = '3'
characterSet[4] = '4'
characterSet[5] = '5'
characterSet[6] = '6'
characterSet[7] = '7'
characterSet[8] = '8'
characterSet[9] = '9'
characterSet[10] = 'a'
characterSet[11] = 'b'
characterSet[12] = 'c'
characterSet[13] = 'd'
characterSet[14] = 'e'
characterSet[15] = 'f'
characterSet[16] = 'g'
characterSet[17] = 'h'
characterSet[18] = 'i'
characterSet[19] = 'j'
characterSet[20] = 'k'
characterSet[21] = 'l'
characterSet[22] = 'm'
characterSet[23] = 'n'
characterSet[24] = 'o'
characterSet[25] = 'p'
characterSet[26] = 'q'
characterSet[27] = 'r'
characterSet[28] = 's'
characterSet[29] = 't'
characterSet[30] = 'u'
characterSet[31] = 'v'
characterSet[32] = 'w'
characterSet[33] = 'x'
characterSet[34] = 'y'
characterSet[35] = 'z'
characterSet[36] = 'A'
characterSet[37] = 'B'
characterSet[38] = 'C'
characterSet[39] = 'D'
characterSet[40] = 'E'
characterSet[41] = 'F'
characterSet[42] = 'G'
characterSet[43] = 'H'
characterSet[44] = 'I'
characterSet[45] = 'J'
characterSet[46] = 'K'
characterSet[47] = 'L'
characterSet[48] = 'M'
characterSet[49] = 'N'
characterSet[50] = 'O'
characterSet[51] = 'P'
characterSet[52] = 'Q'
characterSet[53] = 'R'
characterSet[54] = 'S'
characterSet[55] = 'T'
characterSet[56] = 'U'
characterSet[57] = 'V'
characterSet[58] = 'W'
characterSet[59] = 'X'
characterSet[60] = 'Y'
characterSet[61] = 'Z'
characterSet[62] = '\\alpha'
characterSet[63] = '\\beta'
characterSet[64] = '\\gamma'
characterSet[65] = '\\delta'
characterSet[66] = '\\epsilon'
characterSet[67] = '\\zeta'
characterSet[68] = '\\delta'
characterSet[69] = '\\theta'
characterSet[70] = '\\lambda'
characterSet[71] = '\\mu'
characterSet[72] = '\\xi'
characterSet[73] = '\\pi'
characterSet[74] = '\\rho'
characterSet[75] = '\\sigma'
characterSet[76] = '\\tau'
characterSet[77] = '\\phi'
characterSet[78] = '\\chi'
characterSet[79] = '\\psi'
characterSet[80] = '\\omega'
characterSet[81] = '\\Gamma'
characterSet[82] = '\\Delta'
characterSet[83] = '\\Theta'
characterSet[84] = '\\Lambda'
characterSet[85] = '\\Xi'
characterSet[86] = '\\Pi'
characterSet[87] = '\\Sigma'
characterSet[88] = '\\Phi'
characterSet[89] = '\\Psi'
characterSet[90] = '\\Omega'
characterSet[91] = '+'
characterSet[92] = '-'
characterSet[93] = '\\'
characterSet[94] = '/'
characterSet[95] = '\\eq'
characterSet[96] = '%'
characterSet[97] = '<'
characterSet[98] = '>'
characterSet[99] = '('
characterSet[100] = ')'
characterSet[101] = '['
characterSet[102] = ']'
characterSet[103] = '{'
characterSet[104] = '}'
characterSet[105] = '.'
characterSet[106] = ','
characterSet[107] = '\''

def get_tex(index):

    """
    Return the corresponding tex markup for the index.
    """

    return characterSet[index]
