public void run() {
	// read from port
	this.board = AnimatedBoard.read(new StringReader(this.port.receive()));
	init();
	// new empty event list
	EventList eventList = new EventList();
	// same for card list
	CardList cardList;
	// while no victory condition met
	while(!eventList.containsVictory()) {
		// receive card list
		cardList = CardList.read(new StringReader(this.port.receive()));
		// get player selection
		cardList = this.cardPane.selectCards(cardList);
		// send back
		this.port.send(cardList.toXMLString());
		// receive event list
		eventList = EventList.read(new StringReader(this.port.receive()));
		// reset info pane
		this.infoPane.resetPhase();
		// execute each event
		eventList.execute(this.board, this.infoPane);
	}
	// winning player
	String winPlayer = this.board.getRobotByID(this.playerID).getName();
	// winning string
	String winString = "Winning player is: " + winPlayer + "!";
	// 'this' below was autogenerated by Netbeans
	GameDialogs.showMessageDialog("Game Finished", winString, this);
}